# Autogenerated wrapper script for CLASS_jll for x86_64-linux-gnu-cxx03
export class, etc, external

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("CLASS")
JLLWrappers.@declare_executable_product(class)
JLLWrappers.@declare_file_product(etc)
JLLWrappers.@declare_file_product(external)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_executable_product(
        class,
        "bin/class",
    )

    JLLWrappers.@init_file_product(
        etc,
        "etc",
    )

    JLLWrappers.@init_file_product(
        external,
        "external",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
